name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Pack
        run: |
          dotnet build Fresnel.Audio/Fresnel.Audio.csproj -c Release
          dotnet pack Fresnel.Audio/Fresnel.Audio.csproj -c Release --no-build -o artifacts

      - name: Push
        shell: pwsh
        run: |
          Get-ChildItem -Path artifacts -Filter *.nupkg -File | ForEach-Object {
            dotnet nuget push $_.FullName -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate --source https://api.nuget.org/v3/index.json
          }
